//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace InShow.GenereatedModels
{
	/// <summary>Email folder</summary>
	[PublishedContentModel("EmailFolder")]
	public partial class EmailFolder : Perplexmail
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "EmailFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EmailFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EmailFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BCC
		///</summary>
		[ImplementPropertyType("bcc")]
		public Newtonsoft.Json.Linq.JToken Bcc
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("bcc"); }
		}

		///<summary>
		/// CC
		///</summary>
		[ImplementPropertyType("cc")]
		public Newtonsoft.Json.Linq.JToken Cc
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("cc"); }
		}

		///<summary>
		/// From
		///</summary>
		[ImplementPropertyType("from")]
		public Newtonsoft.Json.Linq.JToken From
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("from"); }
		}

		///<summary>
		/// Log expiration
		///</summary>
		[ImplementPropertyType("logExpiration")]
		public object LogExpiration
		{
			get { return this.GetPropertyValue("logExpiration"); }
		}

		///<summary>
		/// Reply to
		///</summary>
		[ImplementPropertyType("replyTo")]
		public Newtonsoft.Json.Linq.JToken ReplyTo
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("replyTo"); }
		}

		///<summary>
		/// Statistics
		///</summary>
		[ImplementPropertyType("statistics")]
		public Newtonsoft.Json.Linq.JToken Statistics
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("statistics"); }
		}

		///<summary>
		/// To
		///</summary>
		[ImplementPropertyType("to")]
		public Newtonsoft.Json.Linq.JToken To
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("to"); }
		}
	}
}
